### ISSUE TITLE
Possibility to choose the final language ?

### ISSUE THREAD

**Issue by ebouvier31** [addyi/linguee-chrome-plugin#3]
Hi,
Useful plugin.
Each time I used it, the default translation mode is "_English to German_".
I'm not german, so it is possible to choose the destination language in a options-menu ?
Thanks.

**Comment by addyi** [comment]
Hi @ebouvier31 ,

Thanks that you like the plugin.
If you click on the plugin icon in the upper right corner of chrome, an window opens that should give you the option to select the target language. The source language should be automaticly detected by linguee. If this is not the case please let me know. 

Happy to help

addyi

![image](https://user-images.githubusercontent.com/7873672/44736462-9647e580-aaef-11e8-8ebc-b81060a00675.png)
